'use strict';

// Content is data. The markup and styles of the resume stay fixed.
const STORAGE_KEY = 'coforge-resume-v1';
const blankProject = () => ({client:'', duration:'', team:'', technologies:'', role:'', overview:'', responsibilities:''});
const emptyResume = () => ({name:'',designation:'',email:'',phone:'',experience:'',location:'',photo:'',summary:'',skills:['','','','','',''],projects:[blankProject()],education:''});
const example = {
  name:'Manish Kumar', designation:'Data / AI Engineer',email:'manish.44.kumar@coforge.com',phone:'+91 7065382315',experience:'07 years',location:'Greater Noida, India',photo:'',
  summary:'Data & AI Engineer with 7+ years building production-grade data pipelines, ETL/ELT systems, and NLP-driven data extraction across legal, enterprise, and embedded domains. Proven track record cutting manual processing cost by 60% via an automated legal-data extraction pipeline, and improving retrieval speed by 40% on a 40TB on-prem-to-cloud migration. Deep multicloud experience (AWS, Azure) spanning ingestion, governance (RLS, PII masking), warehousing, and BI enablement, with hands-on exposure to embedding-based semantic search and LLM-ready dataset curation.',
  skills:['Python, Py-Spark, ML-AI','Finance, TTH, Legal','Data Factory, Databricks, ADLS, Fabric, Blob Storage, Key Vault, AAD, Event Hub, Git-Action, ADO, S3, Lambda, EC2, ECS, ECR, Kinesis, DynamoDB, Aurora PostgreSQL, IAM Cloud, Snowflake, Cortex AI','AWS, Azure, Snowflake, Microsoft Fabric','POSTGRES, MSSQL, MONGO','GIT'],
  projects:[
    {client:'American Airline',duration:'09-24 to 08-25',team:'22',technologies:'Data Factory, Databricks, ADLS, Fabric, Blob Storage, Key Vault, AAD, Event Hub, GIT, ADO',role:'Sr. Data AI Engineer',overview:'Create pipelines to fetch data from various sources and prepare it for various teams like BI, ML/AI.',responsibilities:'Architected and deployed secure data pipelines for a Chatbot application, implementing Row-Level Security (RLS) and PII masking to ensure strict Data Governance and compliance.\nBuilt an end-to-end ML data pipeline for crew scheduling, enabling incremental batch processing of high-volume operational data.\nDesigned and developed multiple analytical views and multi-stage data models in Snowflake to support BI, Data Science, ML, and AI teams.\nImplemented Dynamic Row-Level Security (RLS) and PII data masking in Snowflake to enforce secure, role-based data access and protect sensitive information.\nDeveloped Azure Data Factory (ADF) and Databricks workflows for large-scale data aggregation and cleaning, directly feeding Power BI dashboards used by executive leadership.'},
    {client:'Lexi Nexis',duration:'08-23 to 07-2024',team:'18',technologies:'S3, Postgres, Snowflake, ADB, ECS, ADF, ADLS',role:'Sr. Data Engineer',overview:'40 TB data migration, Metadata Extraction, Application Modernization, AI knowledge base Data preparation',responsibilities:'Architected an AI/ML pipeline for automated extraction and structuring of legal data from PDF judgments using spaCy NER and custom regex, delivering a 60% reduction in manual processing effort and cost across a corpus spanning thousands of judgments.\nEngineered multi-jurisdictional data ingestion covering Delhi, Allahabad, Odisha, and Patna High Courts, with automatic case categorization and citation-graph extraction to power a unified, queryable legal knowledge base.\nProduced a high-quality annotated legal dataset for downstream LLM applications: citation resolution, judgment summarization, and domain-specific fine-tuning.\nLed the migration of 40TB of legacy XML/CSV data from on-premises servers to AWS S3 and Aurora PostgreSQL, eliminating single points of failure and improving data retrieval speed by 40%.\nBuilt a high-performance full-text search system on Aurora PostgreSQL with metadata tables for cross-jurisdictional correlation and document versioning, reducing search latency by 30% across multi-million-record legal datasets.\nBuilt a REST API-backed vectorization pipeline (FastAPI on Amazon ECS) with embedding-based indexing, enabling low-latency semantic search over structured and unstructured legal content.'},
    {client:'Engimasoft Technology',duration:'07-22 to 06-23',team:'15',technologies:'Dynamo DB, Power BI, SQL, ECS',role:'Data Engineer',overview:'Pipeline creation for batch processing and BI data preparation, ML model training',responsibilities:'Established a real-time Data Acquisition system using MQTT pub-sub and Kafka streaming to InfluxDB applications from various sensors in real time.\nCreated batch processing of data to collect data from InfluxDB to an S3 bucket.\nDeveloped FastAPI based REST APIs to retrieve data from sensors and securely store it in a database.\nCreated an anomaly detection model to identify faulty sensors.'},
    {client:'Robsync Technology',duration:'11-20 to 07-22',team:'8',technologies:'Python, FastAPI, MQTT, Snowflake',role:'Software Developer',overview:'Created various pipeline and data acquisition systems.',responsibilities:'Created Snowflake views for BI tools and enabled RLS and PII masking in sensitive tables.\nCreated automated data loading from multiple sensors to DB.\nDesigned an automated logging system for employees using RFID cards.\nDesigned and developed automation devices using IoT.\nCreated an application for OTA updates to controller devices.\nSynced the user and controlling device using MQTT Pub-Sub protocol.\nDesigned and programmed a variety of IoT devices using C/C++ to control and monitor different appliances.'},
    {client:'Govt Polytechnic College',duration:'04-19 to 05-22',team:'5',technologies:'Python, Flask, Django',role:'Software Developer',overview:'Networking, Virtualization, Web development',responsibilities:'Set up and maintained multiple systems and NAS infrastructure, ensuring seamless data access and collaboration.\nCreated multi-OS sandbox environments for testing, experimentation, and development activities.\nConfigured development and testing environments to support application deployment and troubleshooting.\nProvided infrastructure and application support to ensure system reliability and performance.'}
  ],education:'B.Tech from AKTU University, Lucknow – 2018.'
};
