const { chromium } = require('/Users/manu/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless:true,channel:'chrome'});
  const page = await browser.newPage({viewport:{width:1440,height:1100}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8765');
  await page.screenshot({path:__dirname+'/tmp/app-preview.png',fullPage:false});
  const checkOverflow = async () => {
    const results=await page.locator('.page-content').evaluateAll(nodes=>nodes.map(n=>({height:n.clientHeight,scroll:n.scrollHeight,width:n.clientWidth,scrollWidth:n.scrollWidth})));
    assert(results.every(r=>r.scroll<=r.height+1&&r.scrollWidth<=r.width+1),JSON.stringify(results));return results.length;
  };
  const samplePages=await checkOverflow();
  console.log('Sample pages',samplePages);
  await page.locator('.resume-page').first().screenshot({path:__dirname+'/tmp/resume-preview.png'});
  await page.getByLabel('Full name',{exact:true}).fill('Example <script>alert(1)</script>');
  await page.waitForTimeout(250);
  assert((await page.locator('.profile-name').textContent()).includes('<script>'));
  await page.reload();
  console.log('Persistence checked');
  assert.equal(await page.getByLabel('Full name',{exact:true}).inputValue(),'Example <script>alert(1)</script>');
  await page.locator('#resume-form details').nth(1).locator('summary').click();
  await page.getByLabel('Summary',{exact:true}).fill('A long professional summary describing delivery and leadership. '.repeat(160));
  await page.waitForTimeout(300);await checkOverflow();
  console.log('Long summary checked');
  const before=await page.locator('.page-shell').count();
  await page.getByLabel('Summary',{exact:true}).fill('X'.repeat(12000));
  await page.waitForTimeout(300);await checkOverflow();
  assert.equal((await page.locator('.summary-row').allTextContents()).join(''),'X'.repeat(12000));
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.evaluate(()=>localStorage.clear());await page.reload();
  await page.setViewportSize({width:1440,height:1100});
  await page.emulateMedia({media:'print'});await checkOverflow();
  await page.screenshot({path:__dirname+'/tmp/print-preview.png',fullPage:false});
  assert.equal(await page.locator('.editor').isVisible(),false);
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({samplePages,longSummaryPages:before,checks:['page bounds','safe text rendering','local draft persistence','long text pagination','unbroken text preservation','mobile width','print isolation','no runtime errors']}));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
